dist: xenial
sudo: required 
language: python
python: 3.7
services: 
    - docker 
before_install:
#     # install heroku CLI 
#   - wget -qO- https://toolbelt.heroku.com/install.sh | sh 
#   # login to heroku
#   - echo "$ HEROKU_PASSWORD" | docker login -u "$ HEROKU_USERNAME" --password-stdin registry.heroku.com 
  - docker-compose build -e PORT=80

# script:
#   - uvicorn app.main:app 
services:
  - mongodb

deploy:
    provider: heroku
    api_key:
        secure: "JnyMwqwHw5QQNhE+UEeOTPWDNhPUQ/i8H4dLUJape92APy82dJPRVIpsC0mlJxfm/vDDaXQrP6APztNWT9VAYRi727JCgIwsYngVJVh/k5DvzQLtQI5LYsQesfF/wkkhzRhkcCsL3gF9vFC8LpIR9rwFEryqbkr+G/15b6F2UeJm83FuQcqF2RrFkBmDcEezkLLHAWxnjByuJN9kCiXsIu2+6LW9y0g+hvooGtDbZZNudZ3nfrmm5QzaBRURtc+dIJSAw1XeA9TzLgwUca7Rt+fpWaZdVR4K14JfuZexxGNY84DgzUMjn0xQzLeLZbNIaLBj1S6ZIKXwJqJEuxLZOCKLnD6R7q1oXRGoyRKSTQeT9chyXMreQyV8xYzS7TOuGVWIIOIs2C2qDtVtbkvsCwT9iW1A0ahSrUOUWtgaKuNPNNhcgYxDc1kotyUMeE7EbI436zY/eaTbvgiEJQZoxCexzvt+vhz4yp33UCAe9UIk6RN9XhGjsl1wT0xfn82PC16mlyOoA04gdc4Cva0sbHmUi2RR4nEOngTvVq4MoR/+0dYp6qvQlRq+9tR78IpGAcz9ZBS67BeBZQQ+I+8EJfkHTk65/SLqLtfjpmxgSF2JY77oz4tNrcNz3Jwx30uSJvtqepaSLICvCCrXWGx1Ld3OUkOIqbJzTQPf+6oosMU="
    app: tickets-test-api
    on:
        repo: hassan11196/tickets-test-api
    